a= int(input("Enter the first value "))
b= int(input("Enter the second value "))

print("addition",a+b)
print("substraction",a-b)
print("mul",a*b)
print("division",a/b)
print(a//b)
print(a**a)
print(a**b)